import React, { useEffect, useMemo, useState } from "react";
import { Box, Text, useApp, useInput, useStdout } from "ink";
import { applyTerminalAnswer, answerKeyForInput, canFinish, completionSummary, EXAM_DURATION_MS, terminalDashboardMetrics, terminalSessionSummary, wrongAnswerReview } from "./terminalQuiz.mjs";

const h = React.createElement;
const DAY = 24 * 60 * 60 * 1000;
function Line({ children, ...props }) { return h(Text, props, children); }
function colorRole(enabled, role) { return enabled ? role : undefined; }
function Bar({ answers, total, unicode, enabled }) { const width = 24; const correct = answers.filter((answer) => answer.correct).length; const incorrect = answers.length - correct; const correctWidth = Math.round((correct / Math.max(1, total)) * width); const incorrectWidth = Math.round((incorrect / Math.max(1, total)) * width); const filled = unicode ? "█" : "#"; const empty = unicode ? "░" : "-"; return h(Line, null, h(Line, { color: colorRole(enabled, "green") }, filled.repeat(correctWidth)), h(Line, { color: colorRole(enabled, "red") }, filled.repeat(incorrectWidth)), h(Line, { color: colorRole(enabled, "gray") }, empty.repeat(Math.max(0, width - correctWidth - incorrectWidth))), ` ${answers.length}/${total}`); }

export function TerminalApp({ bank, states, events, deviceId, appendEvent, now = Date.now(), plan, sessionId, resumeAnswers = [], onDone }) {
  const { exit } = useApp(); const { stdout } = useStdout(); const enabled = Boolean(stdout?.isTTY) && !process.env.NO_COLOR && process.env.TERM !== "dumb"; const unicode = !process.env.CCSE_ASCII && process.env.TERM !== "dumb";
  const initialStates = useMemo(() => ({ ...states }), [states]); const queue = useMemo(() => plan?.questions?.length ? plan.questions : bank, [plan, bank]);
  const [currentIndex, setCurrentIndex] = useState(resumeAnswers.length); const [current, setCurrent] = useState(() => queue[resumeAnswers.length] ?? queue[0] ?? bank[0]); const [answers, setAnswers] = useState(resumeAnswers); const [feedback, setFeedback] = useState(null); const [startedAt, setStartedAt] = useState(Date.now()); const [completed, setCompleted] = useState(false); const [message, setMessage] = useState(""); const [remainingMs, setRemainingMs] = useState(plan?.durationMs ?? EXAM_DURATION_MS);
  const total = Math.min(25, queue.length);

  useEffect(() => { if (completed) return undefined; const timer = setInterval(() => setRemainingMs(Math.max(0, (plan?.startedAt ?? now) + (plan?.durationMs ?? EXAM_DURATION_MS) - Date.now())), 1000); return () => clearInterval(timer); }, [completed, now, plan]);
  useEffect(() => { if (!feedback || answers.length >= total) return undefined; const timer = setTimeout(() => { const nextIndex = currentIndex + 1; setCurrentIndex(nextIndex); setCurrent(queue[nextIndex] ?? bank[0]); setFeedback(null); setStartedAt(Date.now()); }, 500); return () => clearTimeout(timer); }, [feedback, answers.length, total, currentIndex, queue, bank]);

  const finish = () => { if (completed) { exit(); return; } if (!canFinish(answers)) { setMessage(`Answer ${total - answers.length} more question${total - answers.length === 1 ? "" : "s"} before pressing Enter.`); return; } const summary = completionSummary(answers, initialStates, states, bank); onDone?.(summary); setCompleted(true); };
  useInput((input, key) => {
    if (key.ctrl && input === "c") { exit(); return; }
    if (key.return) { finish(); return; }
    const answerKey = answerKeyForInput(input); if (!answerKey || !current?.options?.[answerKey] || answers.length >= total || feedback) return;
    const timestamp = Date.now(); const correct = answerKey === current.answer; const event = { eventId: `${deviceId}-${sessionId ?? "session"}-${timestamp}-${current.id}-${answers.length}`, deviceId, timestamp, type: "ANSWER_RECORDED", payload: { questionId: current.id, answer: answerKey, selected: answerKey, correct, responseMs: Math.max(0, timestamp - startedAt), sessionId } };
    applyTerminalAnswer(states, event); appendEvent(event); setAnswers((previous) => [...previous, { correct, responseMs: event.payload.responseMs, questionId: current.id, selected: answerKey }]); setFeedback({ correct, selected: answerKey }); setStartedAt(timestamp); setMessage("");
  });
  const summary = terminalSessionSummary(answers); const metrics = terminalDashboardMetrics(bank, states, events, now, answers); const mode = plan?.mode ?? "coverage";
  if (completed) { const done = completionSummary(answers, initialStates, states, bank); const reviews = wrongAnswerReview(answers, bank); return h(Box, { flexDirection: "column", width: Math.min(stdout?.columns ?? 80, 96), paddingX: 1 }, h(Line, { bold: true, color: colorRole(enabled, "cyan") }, "CCSE PREP · SESSION COMPLETE"), h(Line, { marginTop: 1, bold: true }, `Score ${done.correct}/${done.answered} · ${Math.round(done.accuracy * 100)}% · ${done.passed ? "PASS" : "REVIEW"}`), h(Line, null, `Safety target: ${done.passed ? "met" : "not met"} (${done.correct}/${25}, target ${20})`), h(Line, null, `Weakest task: ${done.weakestTask ? `Tarea ${done.weakestTask}` : "—"}`), h(Line, { marginTop: 1, color: colorRole(enabled, done.passed ? "green" : "yellow") }, done.unlockMessage), h(Line, null, done.nextAction), h(Box, { marginTop: 1, flexDirection: "column" }, ...Object.entries(done.byTask).map(([task, value]) => h(Line, { key: task }, `Tarea ${task}: ${value.correct}/${value.answered}`))), reviews.length > 0 && h(Box, { marginTop: 1, flexDirection: "column" }, h(Line, { bold: true, color: colorRole(enabled, "yellow") }, "Missed answers"), ...reviews.flatMap((review, index) => [h(Line, { key: `${index}-q` }, review.question), h(Line, { key: `${index}-a` }, `✗ ${review.wrong} → ✓ ${review.correct}`), h(Line, { key: `${index}-e`, color: colorRole(enabled, "gray") }, `Why: ${review.explanation}`)])), h(Line, { marginTop: 1, color: colorRole(enabled, "gray") }, "Press Enter to close · Ctrl-C Exit")); }
  const minutes = Math.floor(remainingMs / 60000); const seconds = String(Math.floor((remainingMs % 60000) / 1000)).padStart(2, "0"); const optionLines = ["a", "b", "c"].filter((key) => current?.options?.[key]).map((key) => h(Line, { key, color: colorRole(enabled, feedback && !feedback.correct && feedback.selected === key ? "red" : feedback && key === current.answer ? "green" : undefined) }, `${key === "a" ? "J" : key === "b" ? "K" : "L"}  ${current.options[key]}`));
  return h(Box, { flexDirection: "column", width: Math.min(stdout?.columns ?? 80, 96), paddingX: 1 }, h(Box, { justifyContent: "space-between" }, h(Line, { bold: true, color: colorRole(enabled, "cyan") }, "CCSE PREP"), h(Line, { color: colorRole(enabled, "gray") }, `${mode} · ${summary.answered}/${total} · ${minutes}:${seconds}`)), h(Line, { color: colorRole(enabled, "gray") }, "────────────────────────────────────────────────────────"), h(Box, { justifyContent: "space-between" }, h(Line, null, `Due ${metrics.due} · Weak ${metrics.weak} · Learning ${metrics.learning} · Mastered ${metrics.mastered}`), h(Line, { color: colorRole(enabled, "yellow") }, `Exam ${Math.max(0, Math.ceil((new Date("2026-09-24").getTime() - now) / DAY))}d`)), h(Box, { marginTop: 1, flexDirection: "column" }, h(Line, { color: colorRole(enabled, "gray") }, `Task ${current?.task ?? "—"} · Question ${summary.answered + 1} of ${total}`), h(Line, { bold: true }, current?.question ?? "No questions available."), ...optionLines), h(Box, { marginTop: 1 }, h(Bar, { answers, total, unicode, enabled })), message && h(Line, { marginTop: 1, color: colorRole(enabled, "yellow") }, message), h(Line, { marginTop: 1, color: colorRole(enabled, "gray") }, summary.answered >= total ? "Finishing session…" : "J/K/L Select Answer · Enter to finish · Ctrl-C Exit"));
}

export async function runTerminalTui(options) { const { render } = await import("ink"); return new Promise((resolve) => { const instance = render(h(TerminalApp, { ...options, onDone: (summary) => options.onDone?.(summary) }), { exitOnCtrlC: false }); instance.waitUntilExit().then(() => resolve(undefined)); }); }
